version: "3.8"

services:
  nginx:
    build: services/nginx/.
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    build: services/wordpress/.
    container_name: wp
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  mariadb:
    build : services/mariaDB/.
    container_name: mariadb
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
networks:
  inception:
