version: "3.8"

services:
  nginx:
    build: services/nginx/.
    container_name: nginx
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/paghe/data/web:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  wordpress:
    build: services/wordpress/.
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  mariadb:
    build: services/mariaDB/.
    container_name: mariadb
    volumes:
      - /home/paghe/data/database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wordpress:  # Define the volume once here
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/paghe/data/web
  
    #mariadb:
    # driver: local
    # driver_opts:
    #type: none
    # o: bind
    # device: /Users/apaghera/Documents/Inception/srcs/database

      

networks:
  inception:

