CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
CREATE USER IF NOT EXIST $MYSQL_USER@'%' IDENTIFIED BY $MYSQL_PASSWORD;
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO $MYSQL_USER@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
